version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1

jobs:
  setup-node:
    docker:
      - image: cimg/node:22.11-browsers # Use a compatible Node.js image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Verify Node.js Version
          command: node -v

workflows:
  build:
    jobs:
      - setup-node
      - cypress/run:
          cypress-command: npx cypress run --headless
          start-command: npm run dev
