version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11-browsers # Node.js image with browsers for Cypress
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci # Use `npm ci` for clean installs in CI environments
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  build:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Build the Next.js Application
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .next # Persist the Next.js build folder for testing

  test:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/project
      - checkout
      - run:
          name: Install Cypress Dependencies
          command: npm install # Ensure Cypress is installed for the test step
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
