version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11-browsers
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build the Next.js Application
          command: npm run build

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
