version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11-browsers
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci

  start_dev_server:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Start Dev Server
          command: npm run dev &
      - run:
          name: Wait for Dev Server to Start
          command: |
            until curl -s http://localhost:3000 > /dev/null; do
              echo "Waiting for server to start..."
              sleep 2
            done

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - install_dependencies
      - start_dev_server:
          requires:
            - install_dependencies
      - test:
          requires:
            - start_dev_server
