version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11-browsers # Use a compatible Node.js Docker image

workflows:
  build:
    jobs:
      - cypress/run:
          executor: node-executor # Use the updated Node executor
          cypress-command: npx cypress run --headless
          start-command: npm run dev
