version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1

executors:
  node-executor:
    docker:
      - image: cimg/node:22.11-browsers # Use the Node.js browser image for Cypress compatibility
    working_directory: ~/project

workflows:
  build:
    jobs:
      - cypress/run:
          executor: node-executor
          cypress-command: npx cypress run --headless # Run Cypress tests in headless mode
          start-command: npm run dev # Use `npm run dev` to start the Next.js dev server
          wait-on: http://localhost:3000 # Wait for the Next.js dev server to be ready
          browser: chrome # Specify Chrome browser for Cypress tests
